services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx-tut
    restart: unless-stopped
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
  
  server-1:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - 7000:3000
    volumes:
      - ./server:/app
      - /app/node_modules

  server-2:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - 8000:3000
    volumes:
      - /app/node_modules

  server-3:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - 9000:3000
    volumes:
      - ./server:/app
      - /app/node_modules